#The time turner will be purchasable from the shop or found in the closet. Not sure which yet. Maybe given by Snape.
#NEEDS REVISION
label yh_intro_scene_1:
    #Hermione enters the office uninvited the morning after finding the time turner
    her "Professor, I think we need to stop these meetings."
    m "What? Why? Are you worried about the type of person you're becoming?"
    her "No it's not that... I'm missing too much class."
    m "What? But you come here before classes?"
    her "Not every class. Professor Sprout starts extra curricular Herbology classes at 6 o'clock."
    her "As well as Professor Slughorn's meetings for advanced students after potions class in the evening."
    her "These are opportunities that I can't afford to be missing. My grades have already started to decline..."
    her "(Although only in that nasty Snape's class...)"
    m "So you're going to pick personal gain over Gryffindor winning the house cup this year?"
    her "Well... I would love to keep being able to earn points for my house."
    her "But not at the expense of my education!"
    m "What about the disappointed look on everyone's face when Gryffindor loses to Slytherin?"
    her "I know, I know! If there were any other way I would keep going!"
    m "Any other way?"
    her "ANY!"
    m "Well you're in luck, I've recently come into possession of a powerful magical artifact that could solve our problems."
    her "Really?"
    m "Really. Have you ever heard of a \'time turner\'?"
    her "No I haven't... What does it do?"
    m "It allows you to turn back time. So for example you could spend your mornings in here, turn back time and then go to your extra classes or whatever."
    her "REALLY?! That would be great!"
    her "I'd get to win the house cup and get great grades! Thank you Professor!"
    m "Well I expect you to be grateful for such a powerful gift."
    her "Of course [genie_name] anything you want!"
    ">You hand her the time turner."
    her "This is amazing! I can even take multiple subjects at once!"
    ">She starts turning the dial."
    her "So how far back does each turn take you?"
    m "About 15 minutes by my reckoning."
    her "That little?"
    her "I'll need to turn it back at least 100 times to get to the start of the week."
    m "Why so far back? I'm not sure that that's a good idea..."
    ">She keeps turning the dial."
    her "Well Professor Sprout started her course earlier this week and I don't want to miss any lessons"
    her "Plus this of all the extra study that this will allow me to do!"
    her "I might need longer than a week..."
    her "Maybe two!"
    m "I think you should slow dow-"
    her "I'll only do a month then, just to make it even!"
    her "But Imagine if I started the favours last year! Gryffindor would never lose!"
    ">Hermione starts turning the dial even faster"
    m "I really think that you should slow down!"
    her "Ok, ok I'll stop here."
    ">The dial keeps spinning."
    her "What? It's turning on it's own now!"
    m "Well stop it!"
    her "How, I don't know how!"
    m "Just grab it!"
    her "Um... ah...."
    ">She tries to stop the spinning to no avail."
    her "I can't stop it!"
    m "Well do something!"
    her "It keeps getting faster!"
    her "What do I-"
    ">Hermione goes to throw the time turner on the ground, smashing it."
    "*BOOOM*"
    #magic effect
    her "*cough* *cough* *cough*"
    her "What were you thinking!"
    m "What was I thinking?"
    her "Why did you give me a broken time turner?"
    m "Broken? YOU BROKE IT!"
    her "Hardly, I was just using it how I was told."
    m "It was supposed to be for you to go back an hour or two, Not to relive an entire year!"
    lher "Well you should have warned me!"
    her "Who said that?"
    #Hermini appears
    lher "You. Well me."
    her "..."
    m "..."
    her "WHO ARE YOU?"
    lher "Isn't it obvious? I'm you."
    lher "Well a younger version of you."
    her "How young? And how is this possible?"
    lher "I'm not sure how young I am. I'm guessing it was however many times we turned the time turner when we smashed it."
    m "I told you you shouldn't have smashed it."
    her "Shut up Professor! This is all your fault!"
    m "My fault?"
    her "Hmmph!"
    her "Well at least fix it!"
    lher "Yeah!"
    m "I'm not sure how I would."
    her "You're Professor Dumbledore! The most powerful wizard in the world! If you can't fix it then no one can!"
    m "Well I suppose I could..."
    m "(I have no idea how to fix this...)"
    m "But it would take some time to work out."
    m "And besides, isn't this what you wanted."
    her "I didn't want a little clone of myself!"
    m "Can't she go to your classes?"
    her "Of course no-"
    lher "Yes I can!"
    her "What, how?"
    lher "We share the same memories silly."
    her "We do?"
    lher "I guess you wouldn't be able to tell because you have all my memories anyway but I remember all your classes."
    her "You do?"
    lher "Mmmhmmm. Remember potions yesterday, you almost got the pepperup potion wrong because you didn't cut the mandrake root correctly."
    her "Wow, I guess we do share the same memories."
    lher "Well not all of them. I can't really recall anything that goes on outside of class."
    her "So you don't remember what I come here for?"
    lher "Nope!"
    her "Well that's probably for the best."
    lher "What do you come here for?"
    her "Ummmmmmm you wouldn't understand..."
    lher "Why not. I'm as smart as you are remember."
    her "It's not about being smart."
    lher "Then what are you doing here?"
    m "She's helping me with some experiments."
    lher "Oh really? That sounds super fun!"
    lher "What sort of experiments?"
    m "Social experiments mostly. And as a reward I pay her in house points."
    m "Isn't that right Miss Granger?"
    her "That's one way to put it..." #Glaring look
    lher "Well I want to help to!"
    her "You can't-"
    m "I don't see a problem with it."
    her "WHAT! but she's so young!"
    lher "What does my age have to do with it? I'm as smart and capable as you are!"
    m "Exactly! There's no problem."
    her "Well I suppose not..."
    her "Just don't try anything funny with her Professor."
    m "Me? Never."
    her "..." #Glaring
    lher "Yay! This is going to be so great! We're going to be the smartest girl in school and we get to win the house cup!"
    her "Don't get too excited."
    m "Well you two better head to class. I think I've kept you long enough."
    lher "He's right, if we don't leave now I'll miss History of magic!"
    her "Whatever, come on, let's go mini-me."
    lher "Hey! I am not mini!"
    her "Yes you are! Little Hermini!"
    lher "You're such an idiot!"
    ">Both Hermiones leave your office still arguing."
    m "Huh, not sure that could have been any stranger..."

#Hermiones return to Genie's office after classes
label yh_intro_scene_2:
    ">The two Hermiones enter your office."
    her "Have you worked out how to fix this problem yet?"
    lher "Have you Professor?"
    m "Unfortunately not. Apparently Miss Granger is the first person to ever try using a time turner to go back a year and then smash it on the ground afterwards."
    her "Come on Professor, we can't keep walking around the school together. People are asking questions. A lot of questions."
    lher "She's right, We can only avoid answering them for so long."
    m "Can't you just say she's your little sister?"
    her "Everyone knows I don't have a sister."
    lher "Plus I wouldn't be going to the same classes if I was younger than her."
    m "Ok, ok, until I get this fixed what about you say that your Hermione's cousin."
    her "I suppose that would work..."
    lher "But why would I only be joining Hogwarts now?"
    her "And why would she be in my classes?"
    m "Can't you two figure anything out for yourselves?"
    her "Sorry they don't teach how to deal with a time clone of yourself in Herbology!"
    lher "I mean they cover something similar in astronomy..."
    her "Quiet down you."
    lher "Hmmmph..."
    m "Let's just say that she lived in Australia until her parents recently died."
    lher "But I don't sound Australian..."
    her "And they have no magic school there!"
    lher "And people would ask so many more questions!"
    m "Well I'll leave it up to you two to figure out the specifics."
    m "In the mean time I'll arrange for you to be enrolled in all the same classes as Hermione."
    lher "Extra electives too please!"
    m "What?"
    her "Well seeing as how we retain the same memory of classes it only makes sense that she takes classes that I would otherwise be unable to."
    m "Ok, I'll make sure that you're enrolled in every bloody subject there is."
    lher "Yay, this is going to be great!"
    her "I know! We can even take two transmutation subjects now!"
    m "What about how old you look? Won't people ask questions about that?"
    lher "I'll just tell them how much smarter I am than them!"
    m "(I'm sure that'll go down well.)"
    m "Well then, one final thing. I expect one of you to be available at all times."
    her "Of course sir."
    lher "Whichever one of us you summon, the other will just cover for."
    m "Ok, well you two had better had back to your dorm before people start getting suspicious."
    lher "about that, Will I be getting my own bed?"
    m "Can't you share with Hermione?"
    her "In a single bed?"
    m "Oh come on, she's tiny! It can't be that cramped."
    lher "I don't really mind..."
    m "See? No problem."
    her "Fine, just don't hog the sheets."
    lher "says you..."
    ">They leave the office, still arguing over the bed situation."
    m "I'm not sure what I'm signing up for here..."
    ">Hermini can now be summoned from the door!"

#First time you summon Hermini
label yh_intro_scene_3:
    ">Young Hermione enters your office."
    lher "You called for me Professor?"
    m "I did."
    lher "Is it to participate in some experiments?"
    m "Indeed it is."
    lher "Well what type of experiments are they?"
    lher "Will you be making me drink some weird new potion that you've made?"
    lher "Will you be teaching me new spells?"
    lher "Will you be showing me some new magical animals?"
    lher "Will you be-"
    m "These are what are known as social experiments."
    lher "Social experiments?"
    m "Yes. They involve me giving you certain kinds of stimulus and then recording your actions."
    lher "Really? What kind of stimulus?"
    m "It's really quite innocent. Things like patting you on the head and asking certain types of questions."
    lher "Patting me on the head?"
    m "It's to record how you interact with human contact."
    lher "I'm not sure how that will help with anything..."
    m "Quite the opposite. Being able to understand our emotions and how we react to them is the very key of magic."
    lher "Well if you say so Professor I trust you!"
    m "Good! Shall we start with a simple experiment then?"
    lher "Ok, what is it going to be?"
    menu:
        "-Pat on the head-":
            m "We'll start with something simple. Stay where you are."
            lher "ok..."
            ">You walk over to Hermini"
            m "Are you ready?"
            lher "I suppose."
            m "Ok, here we go."
            ">You start patting her on the head."
            lher "..."
            lher "Is this it?"
            m "This is it."
            ">You keep patting her."
            lher "How long do I have to keep this up?"
            m "Not too much longer."
            lher "Is this really an experiment?"
            m "It is, tell me how this makes you feel."
            lher "Confused."
            m "Anything else?"
            lher "Slightly annoyed"
            m "Why is that?"
            lher "Because the school headmaster is patting me on the head..."
            lher "This is dumb sir. Are you really learning anything from this?"
            lher "Or is it just an excuse for a lonely old man to touch someone else for a change?"
            m "That's not a very nice thing to say."
            lher "Well making me miss class so that you can pat me on the head isn't very nice either."
            m "I suppose you're right. That's all for now then."
        "-Talk to me-":
            m "How about a simple little conversation."
            lher "That seems easy enough! What are we going to talk about?"
            m "Let's talk about how much you remember about big Hermione."
            lher "Alright."
            m "Let's start off with her memories. How much do you remember?"
            lher "Of her life? Pretty much just all of her classes."
            m "You don't remember coming here?"
            lher "I remember that she comes here... not what she does in here though."
            m "So all of the experiments and favours?"
            lher "Favours?"
            m "Well sometimes I'll ask Hermione to do something for me in exchange for points."
            lher "Something other than an experiment?"
            m "Yes, although it is worth more points."
            lher "More points? Are you going to ask me to do some favours?"
            m "Once I get to know you a little better."
            lher "Hmmmm... Why couldn't we do them now?"
            m "You're an eager beaver aren't you. All good things come to those who wait little miss."
            lher "Hmmmph. I certainly remember you being eccentric..."

    lher "Can I go back to class now?"
    m "You may."
    lher "Wait, what about my points? You said that you were paying big Hermione."
    m "Indeed I am. What seems like a fair amount to you?"
    lher "Three points?"
    m "Three seems a little high don't you think?"
    lher "I guess so..."
    m "How about an even two?"
    lher "Ok then."
    lher "(Is that enough? I'll have to ask big me...)"
    m "Have a nice day Miss Granger."
    lher "You too professor."
    ">Hermione returns to classes."
    ">You can now initiate favours with Hermini."













